<a href="https://colab.research.google.com/github/Yair-BD/ML-AI-Tutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.zeros(3)
a

array([0., 0., 0.])

ווקטור הוא מערך חד מיימדי

In [ ]:
one_dimantion=  np.array([10,20,384,5,6,7,8,445,3334,334455])
one_dimantion


array([    10,     20,    384,      5,      6,      7,      8,    445,
         3334, 334455])

מטריקס הוא מערך בעל יותר מווקטור אחד

In [ ]:
two_dimantion = np.array([[1,2,3],[4,5,6]])
two_dimantion

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
 t_row_Columns= two_dimantion.shape
 t_row_Columns

(2, 3)

In [ ]:
first_in = one_dimantion[0]
first_in

10

In [ ]:
from_1_2 = one_dimantion[0:3]
from_1_2

array([ 10,  20, 384])

טנסור הוא מערך דו מיימדי .

In [31]:
two_vectors_1 = np.array([[77,88,99],[44,55,66]])
two_vectors_1

array([[77, 88, 99],
       [44, 55, 66]])

In [32]:
tensor = np.array([two_dimantion,two_dimantion_1])
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[77, 88, 99],
        [44, 55, 66]]])

In [35]:
second_in = two_dimantion[0,1]
second_in

2

In [39]:
#change _second 
two_dimantion[0,1] = 7
two_dimantion

array([[1, 7, 3],
       [4, 5, 6]])

In [40]:
first_row = two_dimantion[0]
first_row 

array([1, 7, 3])

In [47]:
second_column = two_dimantion[:,1]
second_column

array([7, 5])

In [61]:
if_array = np.array([3,6,2,-6,-4,2,9,8,-4])
if_array

array([ 3,  6,  2, -6, -4,  2,  9,  8, -4])

In [52]:
if_array>3

array([False,  True, False, False, False, False,  True,  True, False])

In [53]:
if_array[if_array>3]

array([6, 9, 8])

In [56]:
a = if_array[if_array>3]         # [ 8. 13.  4.]
b = if_array[(if_array>3)&(if_array<9)] # [8. 4.]
c = if_array[(if_array<3)|(if_array>9)] # [-2.  13.   1.2]

In [57]:
a

array([6, 9, 8])

In [58]:
b

array([6, 8])

In [59]:
c

array([ 2, -6, -4,  2, -4])

In [62]:
2*a

array([12, 18, 16])

הכפלה של מערכים מכפילה כל מיקום בכל מיקום בצורה חח"ע 

In [65]:
a*np.array([1,2,3])

array([ 6, 18, 24])

נסיוח מחדש של המערך 

In [73]:
a = np.array([1,2,3,4,5,6,8,9])
shaping = a.reshape(2,2,2)#עמודות,שורות,מספר ממדים
shaping

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 9]]])