<a href="https://colab.research.google.com/github/Yair-BD/ML-AI-Tutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
one_dimantion=  np.array([10,20,384,5,6,7,8,445,3334,334455])
one_dimantion


array([    10,     20,    384,      5,      6,      7,      8,    445,
         3334, 334455])

In [ ]:
two_dimantion = np.array([[1,2,3],[4,5,6]])
two_dimantion

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
 t_row_Columns= two_dimantion.shape
 t_row_Columns

(2, 3)

In [ ]:
first_in = one_dimantion[0]
first_in

10

In [ ]:
from_1_2 = one_dimantion[0:3]
from_1_2

array([ 10,  20, 384])